In [1]:
import plotly.express as px
import pandas as pd

df = pd.read_excel(
    "../data/resultat-ansokningsomgang-2024.xlsx",
    sheet_name="Tabell 3",
    skiprows=5,
)

# goal:
# Antal sökta utbildningar per kommun

df.head()

,Utbildningsområde,SUN5 inriktning,SUN5 inriktning namn,Utbildningsnamn,Beslut,Diarienummer,Flera kommuner,Antal kommuner,Län,Kommun,...,Sökta utbildningsomgångar,Beviljade utbildningsomgångar,Sökta platser per utbildningsomgång,Sökta platser totalt,Beviljade platser utbildningsomgång 1,Beviljade platser utbildningsomgång 2,Beviljade platser utbildningsomgång 3,Beviljade platser utbildningsomgång 4,Beviljade platser utbildningsomgång 5,Beviljade platser totalt
0,Data/IT,481ab,"Utbildningar till programmerare, spel",AI Programmer,Avslag,MYH 2024/3742,Nej,1,Västerbotten,Umeå,...,3,0,30,90,0,0,0,0,0,0
1,Data/IT,481ab,"Utbildningar till programmerare, spel","Forsbergs, Spelutvecklare – Game Programming",Avslag,MYH 2024/4174,Nej,1,Stockholm,Stockholm,...,3,0,20,60,0,0,0,0,0,0
2,Data/IT,481ab,"Utbildningar till programmerare, spel",Futuregames Game Programmer Specialization,Avslag,MYH 2024/3029,Ja,2,Flera kommuner,Flera kommuner,...,3,0,30,90,0,0,0,0,0,0
3,Data/IT,481ab,"Utbildningar till programmerare, spel",Game Programmer,Avslag,MYH 2024/3425,Nej,1,Blekinge,Karlshamn,...,3,0,25,75,0,0,0,0,0,0
4,Data/IT,481ab,"Utbildningar till programmerare, spel",Spelprogrammerare,Beviljad,MYH 2024/3852,Nej,1,Skåne,Malmö,...,4,3,35,140,35,35,35,0,0,105

In [2]:
df["Kommun"].value_counts()

Kommun
Flera kommuner    292
Stockholm         248
Göteborg          157
Malmö              86
Linköping          32
                 ...
Götene              1
Ronneby             1
Västervik           1
Hammarö             1
Leksand             1
Name: count, Length: 104, dtype: int64

In [4]:
px.bar(df["Kommun"].value_counts())

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'variable=count<br>Kommun=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': 'count',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': 'count',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['Flera kommuner', 'Stockholm', 'Göteborg', 'Malmö', 'Linköping',
                          'Solna', 'Jönköping', 'Örebro', 'Västerås', 'Helsingborg', 'Sundsvall',
                          'Skellefteå', 'Umeå', 'Botkyrka', 'Mölndal', 'Växjö', 'Uppsala', 'Lund',
                          'Borås', 'Norrköping', 'Södertälje', 'Trollhättan', 'Nyköping',
                          'Karlshamn', 'Piteå', 'Vänersborg', 'Nässjö', 'Habo', 'Varberg',
                          'Halmstad', 'Karlstad', 'Gävle', 'Hudiksvall', 'Örnsköldsvik',
                          'Karlskrona', 'Luleå', 'Borlänge', 'Arboga', 'Sigtuna', 'Hässleholm',
                          'Skövde', 'Kalmar', 'Eslöv', 'Filipstad', 'Härryda', 'Eskilstuna',
                          'Lidköping', 'Kristianstad', 'Nynäshamn', 'Boden', 'Uddevalla',
                          'Ljungby', 'Östersund', 'Härnösand', 'Olofström', 'Oskarshamn',
                          'Kramfors', 'Arvika', 'Skara', 'Värnamo', 'Staffanstorp', 'Ängelholm',
                          'Falun', 'Sandviken', 'Tibro', 'Norrtälje', 'Forshaga', 'Falkenberg',
                          'Nacka', 'Sunne', 'Båstad', 'Tranås', 'Krokom', 'Enköping', 'Älmhult',
                          'Vellinge', 'Trelleborg', 'Sollefteå', 'Upplands-Bro', 'Åre', 'Klippan',
                          'Håbo', 'Lindesberg', 'Eksjö', 'Haninge', 'Mörbylånga', 'Svedala',
                          'Kungsbacka', 'Sollentuna', 'Höör', 'Mariestad', 'Katrineholm', 'Osby',
                          'Mora', 'Markaryd', 'Hultsfred', 'Askersund', 'Motala', 'Kungälv',
                          'Götene', 'Ronneby', 'Västervik', 'Hammarö', 'Leksand'], dtype=object),
              'xaxis': 'x',
              'y': {'bdata': ('JAH4AJ0AVgAgAB8AFgAWABQAEgAQAA' ... 'ABAAEAAQABAAEAAQABAAEAAQABAA=='),
                    'dtype': 'i2'},
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'title': {'text': 'variable'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'Kommun'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'value'}}}
})

In [ ]:
df.query("Utbildningsområde == 'Data/IT'")[
    "Kommun"].value_counts().reset_index().rename({"count": "Ansökta utbildningar"}, axis=1)

             Kommun  Ansökta utbildningar
0    Flera kommuner                   292
1         Stockholm                   248
2          Göteborg                   157
3             Malmö                    86
4         Linköping                    32
..              ...                   ...
99           Götene                     1
100         Ronneby                     1
101       Västervik                     1
102         Hammarö                     1
103         Leksand                     1

[104 rows x 2 columns]